// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcEventsOutputTypes =
  | { proc_name: 'cmd'; output_type: null }
  | { proc_name: 'test_ev'; output_type: null }

export type TauRpcApiInputs =
  | { proc_name: 'update_state'; input_type: string }
  | { proc_name: 'get_window'; input_type: null }
  | { proc_name: 'get_app_handle'; input_type: null }
  | { proc_name: 'test_io'; input_type: [User, number] }
  | { proc_name: 'test_option'; input_type: null }
  | { proc_name: 'test_result'; input_type: User }
  | { proc_name: 'with_sleep'; input_type: null }
  | { proc_name: 'method_with_alias'; input_type: null }
  | { proc_name: 'ev'; input_type: string }

export type User = { uid: number; first_name: string; last_name: string }

export type TauRpcEventsInputs = { proc_name: 'cmd'; input_type: null } | {
  proc_name: 'test_ev'
  input_type: null
}

export type TauRpcApiOutputTypes =
  | { proc_name: 'update_state'; output_type: null }
  | { proc_name: 'get_window'; output_type: null }
  | { proc_name: 'get_app_handle'; output_type: null }
  | { proc_name: 'test_io'; output_type: User }
  | { proc_name: 'test_option'; output_type: null | null }
  | { proc_name: 'test_result'; output_type: User }
  | { proc_name: 'with_sleep'; output_type: null }
  | { proc_name: 'method_with_alias'; output_type: null }
  | { proc_name: 'ev'; output_type: null }

import { createTauRPCProxy as createProxy } from 'taurpc'

export const createTauRPCProxy = () => createProxy<Router>()

type Router = {
  '': [TauRpcApiInputs, TauRpcApiOutputTypes]
  'events': [TauRpcEventsInputs, TauRpcEventsOutputTypes]
}
