// My header

// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type Error = { type: "Io" } | { type: "Other"; data: string }

export type Update = { progress: number }

/**
 * Doc comments are also generated
 */
export type User = { 
/**
 * The user's id
 */
uid: number; 
/**
 * The user's first name
 */
first_name: string; 
/**
 * The user's last name
 */
last_name: string }

const ARGS_MAP = { '':'{"with_sleep":[],"get_app_handle":[],"test_bigint":["num"],"test_option":[],"test_io":["_user"],"get_window":[],"test_result":["user"],"get_webview_window":[],"multiple_args":["arg","arg2"],"with_channel":["on_event"],"update_state":["new_value"],"ev":["updated_value"],"method_with_alias":[],"vec_test":["arg"]}', 'api.ui':'{"trigger":[],"test_ev":[]}', 'events':'{"test_ev":[],"vec_test":["args"],"multiple_args":["arg1","arg2"],"state_changed":["new_state"]}' }
export type Router = { '': { ev: (updatedValue: string) => Promise<void>, 
get_app_handle: () => Promise<void>, 
get_webview_window: () => Promise<void>, 
get_window: () => Promise<void>, 
method_with_alias: () => Promise<void>, 
multiple_args: (arg: string[], arg2: string) => Promise<void>, 
test_bigint: (num: string) => Promise<string>, 
test_io: (user: User) => Promise<User>, 
test_option: () => Promise<null | null>, 
test_result: (user: User) => Promise<User>, 
update_state: (newValue: string) => Promise<void>, 
vec_test: (arg: string[]) => Promise<void>, 
with_channel: (onEvent: TAURI_CHANNEL<Update>) => Promise<void>, 
with_sleep: () => Promise<void> },
'api.ui': { test_ev: () => Promise<void>, 
trigger: () => Promise<void> },
'events': { multiple_args: (arg1: number, arg2: string[]) => Promise<void>, 
state_changed: (newState: string) => Promise<void>, 
test_ev: () => Promise<void>, 
vec_test: (args: string[]) => Promise<void> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
