// My header

// This file has been generated by Specta. DO NOT EDIT.
import { createTauRPCProxy as createProxy } from '@fltsci/taurpc'
import { ARGS_MAP, type Router } from './bindings'

export type { InferCommandOutput } from '@fltsci/taurpc'

export const createTauRPCProxy = (): ReturnType<typeof createProxy<Router>> =>
  createProxy<Router>(ARGS_MAP)
