// My header
// This file has been generated by TauRPC. Do not edit this file manually.
import { createTauRPCProxy as createProxy, type InferCommandOutput } from '@fltsci/taurpc'
import { ARGS_MAP, type Router } from './bindings'

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
