use heck::ToLowerCamelCase;
use specta::{
    Types,
    datatype::{
        DataType, Field, Fields, Function, NamedReference, NamedReferenceType, Primitive,
        Reference, Struct,
    },
};
use specta_serde::Phase;
use specta_typescript::{Error, Exporter, FrameworkExporter, Typescript, define};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::path::Path;

const FRAMEWORK_HEADER: &str =
    "// This file has been generated by TauRPC. Do not edit this file manually.";

static PACKAGE_JSON: &str = r#"
{
    "name": ".taurpc",
    "types": "index.ts",
    "exports": {
        ".": "./index.ts",
        "./proxy": "./proxy.ts"
    }
}
"#;

/// Export the generated TS types and the runtime client proxy.
///
/// Output is split across two files:
///   - `bindings.ts`: types, `ARGS_MAP`, and `Router`. No npm imports, so
///     Vite's optimizeDeps scanner does not pre-bundle `@fltsci/taurpc`
///     when consumers only `import type` from this file.
///   - `proxy.ts`: the runtime `createTauRPCProxy` factory plus a
///     `InferCommandOutput` re-export.
///
/// By default, if the `export_to` attribute was not specified on the
/// procedures macro, nothing is exported.
pub(super) fn export_types(
    export_path: &'static str,
    args_map: BTreeMap<String, String>,
    ts: Typescript,
    functions: BTreeMap<String, Vec<Function>>,
    mut types: Types,
) -> Result<(), Error> {
    types.iter_mut(|ndt| {
        if let Some(ty) = ndt.ty.as_mut() {
            rewrite_bigints_in_datatype(ty);
        }
    });

    let exporter: Exporter = ts.into();
    let user_header = exporter.header.clone();

    exporter
        .framework_prelude(FRAMEWORK_HEADER)
        .framework_runtime(move |mut exporter| {
            let mut out = String::new();

            out.push_str(&exporter.render_types()?);

            out.push_str("\nexport const ARGS_MAP = ");
            out.push_str(
                &serde_json::to_string_pretty(&args_map)
                    .map_err(|err| Error::framework("error stringify argument map", err))?,
            );
            out.push_str(";\n\n");

            out.push_str(
                &generate_functions_router(&functions, &exporter)
                    .map_err(|err| Error::framework("failed to generate router type", err))?,
            );

            Ok(out.into())
        })
        .export_to(export_path, &types, specta_serde::Format)?;

    let bindings_path = Path::new(export_path);
    let proxy_path = bindings_path.with_file_name("proxy.ts");
    let bindings_stem = bindings_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| Error::framework("", "bindings path has no valid file stem"))?;

    write_proxy_file(&proxy_path, bindings_stem, &user_header)?;

    let normalized = export_path.replace('\\', "/");
    if normalized.ends_with("node_modules/.taurpc/index.ts") {
        let package_json_path = bindings_path
            .parent()
            .ok_or(Error::framework("", "Failed to create 'package.json' path"))?
            .join("package.json");

        std::fs::write(package_json_path, PACKAGE_JSON)
            .map_err(|err| Error::framework("Failed to create 'package.json' file", err))?
    }

    Ok(())
}

/// Write `proxy.ts` -- imports `ARGS_MAP` and `Router` from the sibling
/// bindings file and exports `createTauRPCProxy`. Kept out of bindings.ts
/// so the bindings stay free of npm imports (Vite's optimizeDeps scanner
/// won't pre-bundle `@fltsci/taurpc` when consumers only `import type`).
fn write_proxy_file(
    proxy_path: &Path,
    bindings_stem: &str,
    user_header: &str,
) -> Result<(), Error> {
    let user_prefix = if user_header.is_empty() {
        String::new()
    } else if user_header.ends_with('\n') {
        user_header.to_string()
    } else {
        format!("{user_header}\n")
    };
    let content = format!(
        "{user_prefix}{FRAMEWORK_HEADER}\n\
         import {{ createTauRPCProxy as createProxy, type InferCommandOutput }} from '@fltsci/taurpc'\n\
         import {{ ARGS_MAP, type Router }} from './{bindings_stem}'\n\n\
         export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)\n\
         export type {{ InferCommandOutput }}\n"
    );
    std::fs::write(proxy_path, content)
        .map_err(|err| Error::framework("Failed to write proxy.ts", err))?;
    Ok(())
}

fn generate_functions_router(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
) -> Result<String, Error> {
    let mut router = Struct::named();

    for (path, path_functions) in functions {
        let mut function_names_and_funcs: Vec<_> =
            path_functions.iter().map(|f| (f.name(), f)).collect();
        function_names_and_funcs.sort_by(|a, b| a.0.cmp(b.0));

        let mut path_router = Struct::named();
        for (_, function) in function_names_and_funcs {
            let (name, field) = generate_function_field(function, exporter)?;
            path_router = path_router.field(name, field);
        }

        router = router.field(path.clone(), Field::new(path_router.build()));
    }

    let router_type = exporter.inline(&router.build())?;
    Ok(format!("export type Router = {router_type};\n"))
}

fn generate_function_field(
    function: &Function,
    exporter: &FrameworkExporter,
) -> Result<(String, Field), Error> {
    // apply_phases already validated the phased type graph; the unified-mode
    // validate_exported_command used to re-run here and rejected every command
    // whose type graph contains `skip_serializing_if`, which collides with
    // every struct we apply `serde_with::apply` to. Rely on apply_phases.
    let args = function
        .args()
        .iter()
        .map(|(name, typ)| {
            render_reference_dt_for_phase(typ, Phase::Deserialize, exporter)
                .map(|ty| format!("{}: {ty}", name.to_lower_camel_case()))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");

    let return_ty = if let Some(result) = function.result() {
        if let Some((dt_ok, _dt_err)) = extract_std_result(result, exporter.types) {
            render_reference_dt_for_phase(dt_ok, Phase::Serialize, exporter)?
        } else {
            render_reference_dt_for_phase(result, Phase::Serialize, exporter)?
        }
    } else {
        "void".to_string()
    };

    let name = function.name().split_once("_taurpc_fn__").unwrap().1;
    Ok((
        name.to_string(),
        Field::new(define(format!("({args}) => Promise<{return_ty}>")).into()),
    ))
}

// Render a `DataType` as a reference (or fallback to inline).
// Also handles Tauri channel references.
fn render_reference_dt(dt: &DataType, exporter: &FrameworkExporter) -> Result<String, Error> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = exporter.types.get(r)
        && ndt.name == "TAURI_CHANNEL"
        && ndt.module_path.starts_with("tauri::")
    {
        let generic = if let Some((_, dt)) = named_reference_generics(r).first() {
            match &dt {
                DataType::Reference(r) => exporter.reference(r)?,
                dt => exporter.inline(dt)?,
            }
            .into()
        } else {
            Cow::Borrowed("never")
        };
        Ok(format!("(response: {generic}) => void"))
    } else {
        match &dt {
            DataType::Reference(r) => exporter.reference(r),
            dt => exporter.inline(dt),
        }
    }
}

fn extract_std_result<'a>(
    dt: &'a DataType,
    types: &'a Types,
) -> Option<(&'a DataType, &'a DataType)> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = types.get(r)
        && ndt.name == "Result"
        && (ndt.module_path == "std::result" || ndt.module_path == "core::result")
        && let [(_, ok), (_, err), ..] = named_reference_generics(r)
    {
        return Some((ok, err));
    }

    None
}

fn named_reference_generics(r: &NamedReference) -> &[(specta::datatype::Generic, DataType)] {
    match &r.inner {
        NamedReferenceType::Reference { generics, .. } => generics,
        NamedReferenceType::Inline { .. } | NamedReferenceType::Recursive => &[],
    }
}

fn render_reference_dt_for_phase(
    dt: &DataType,
    phase: Phase,
    exporter: &FrameworkExporter,
) -> Result<String, Error> {
    let dt =
        specta_serde::select_phase_datatype(&rewrite_bigints_for_export(dt), exporter.types, phase);

    render_reference_dt(&dt, exporter)
}

fn rewrite_bigints_for_export(dt: &DataType) -> DataType {
    let mut dt = dt.clone();
    rewrite_bigints_in_datatype(&mut dt);
    dt
}

/// This rewrites any large number types to a smaller type.
/// The newest version of Specta's Typescript exporter will always error on these (and the previous solution which was `BigIntExportBehaviour` has been removed).
/// The recommendations for handling this now are documented here: https://github.com/specta-rs/specta/blob/d578bc055b7c5e6573d1cd723e7be56d33c28e5c/specta-typescript/src/error.rs#L11
///
/// TODO: I (@oscartbeaumont) am going to do a follow up PR to support BigInt's properly in the future but this requires upstream work in Tauri so it's not possible at the moment.
fn rewrite_bigints_in_datatype(dt: &mut DataType) {
    fn rewrite_bigints_in_fields(fields: &mut Fields) {
        match fields {
            Fields::Unit => {}
            Fields::Unnamed(fields) => {
                for field in fields.fields.iter_mut() {
                    if let Some(ty) = field.ty.as_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
            Fields::Named(fields) => {
                for (_, field) in fields.fields.iter_mut() {
                    if let Some(ty) = field.ty.as_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
        }
    }

    match dt {
        DataType::Primitive(primitive) => match primitive {
            Primitive::usize
            | Primitive::isize
            | Primitive::u64
            | Primitive::i64
            | Primitive::u128
            | Primitive::i128
            | Primitive::f128 => {
                // Rewrite bigint primitives to f64 (also rendered as `number`
                // in TS) instead of an opaque `define("number")` reference.
                // The opaque variant is valid in struct/enum/list/value
                // positions but specta-typescript's `validate_map_key` rejects
                // any `Reference::Opaque` -- so a HashMap<i64, V> field would
                // surface as `Invalid map key at HashMap.<map_key>`. f64 is
                // accepted by both `primitive_is_valid_key` and `primitive_dt`.
                *dt = DataType::Primitive(Primitive::f64);
            }
            _ => {}
        },
        DataType::List(list) => rewrite_bigints_in_datatype(&mut list.ty),
        DataType::Map(map) => {
            rewrite_bigints_in_datatype(map.key_ty_mut());
            rewrite_bigints_in_datatype(map.value_ty_mut());
        }
        DataType::Struct(strct) => rewrite_bigints_in_fields(&mut strct.fields),
        DataType::Enum(enm) => {
            for (_, variant) in enm.variants.iter_mut() {
                rewrite_bigints_in_fields(&mut variant.fields);
            }
        }
        DataType::Tuple(tuple) => {
            for item in tuple.elements.iter_mut() {
                rewrite_bigints_in_datatype(item);
            }
        }
        DataType::Nullable(inner) => rewrite_bigints_in_datatype(inner),
        DataType::Reference(Reference::Named(reference)) => {
            if let NamedReferenceType::Reference { generics, .. } = &mut reference.inner {
                for (_, generic) in generics.iter_mut() {
                    rewrite_bigints_in_datatype(generic);
                }
            }
        }
        DataType::Generic(_) | DataType::Reference(Reference::Opaque(_)) => {}
        DataType::Intersection(types) => {
            for ty in types {
                rewrite_bigints_in_datatype(ty);
            }
        }
    }
}
