<script lang="ts">
  import { onMount } from 'svelte'
  import { createTauRPCProxy } from './lib/ipc'

  // The proxy is generated by default according to the Rust configuration
  let taurpc: ReturnType<typeof createTauRPCProxy>
  
  let resultStatus = "Waiting..."

  onMount(() => {
    taurpc = createTauRPCProxy()
  })

  const testResultMode = async () => {
    resultStatus = "Loading..."
    try {
      // Because we set `.error_handling(ErrorHandlingMode::Result)` in Rust,
      // res is now strictly typed as TauRpcResult<User, Error>!
      const res = await taurpc.test_result({
        uid: 42,
        first_name: "Test",
        last_name: "Result"
      })

      
      if (res.status === 'error') {
        // TypeScript knows res.error is of type `Error` (which maps to `{ Other: string }` here)
        resultStatus = `Backend Error (Result Mode): ${JSON.stringify(res.error)}`
      } else {
        // TypeScript knows res.data is `User`
        resultStatus = `Success (Result Mode): ${JSON.stringify(res.data)}`
      }
    } catch (error) {
      resultStatus = `Caught Exception! (This shouldn't happen unless the IPC fundamentally fails): ${error}`
    }
  }
</script>

<div class="error-testing">
  <h2>Error Handling Sandbox</h2>
  <p>Test how the frontend receives <code>Result&lt;T, E&gt;</code> from Tauri commands in Result mode.</p>

  <div class="test-block">
    <h3>New <code>Result</code> Mode</h3>
    <button on:click={testResultMode}>Test <code>test_result</code></button>
    <p>Result: <code>{resultStatus}</code></p>
  </div>
</div>

<style>
  .error-testing {
    border: 1px solid #ccc;
    padding: 1.5rem;
    margin-top: 2rem;
    border-radius: 8px;
    background-color: #fcfcfc;
    box-shadow: 0 2px 4px rgba(0,0,0,0.05);
  }
  .test-block {
    margin-top: 1rem;
    padding: 1rem;
    background-color: #fff;
    border: 1px solid #eee;
    border-radius: 4px;
  }
  button {
    background-color: #2196F3;
    color: white;
    border: none;
    padding: 6px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-weight: bold;
  }
  button:hover {
    background-color: #1976D2;
  }
  code {
    background: #eef;
    padding: 2px 4px;
    border-radius: 4px;
    color: #333;
  }
</style>
